# Generated by Django 5.0.4 on 2024-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='on_trend',
            field=models.BooleanField(default=False),
        ),
    ]
